#' Create Mean Matrix
#'
#' @description
#' Computes a consistency score matrix for a specified k by measuring how
#' frequently each pair of observations is clustered together across subsamples.
#' Each element in the score matrix represents the sum of corresponding -1 and 1
#' values across subsamples, divided by the total number of valid comparisons.
#' This approach excludes zeros, which indicate observations not included in a
#' given resample. The function calls buddies_matrix() to obtain the matrices
#' for this calculation.
#'
#' @param data
#' The dataset to be analyzed
#'
#' @param k
#' The specific number of clusters (k) to evaluate. Defaults to 3.
#'
#' @param subsample_prop
#' Proportion of the dataset to use for each subsample. Defaults to 0.8.
#'
#' @param num_subsamples
#' Number of subsamples to generate. Defaults to 10.
#'
#' @param start_seed
#' Random seed for reproducibility. Defaults to 123.
#'
#' @param cluster_method
#' Specified clustering algorithm
#'
#' @returns
#' Produces a list of two elements. The first element, results, stores the
#' matrices generated by buddies_matrix(). The second element, score, represents
#' the final mean consistency matrix calculated from those results.
#'
#' @export
#'
#' @examples
#' data <- simulate_mvn(n = 10)
#' mean_matrix(data = data, k = 3, subsample_prop = 0.8, num_subsamples = 3,
#'             cluster_method = "kmeans")

mean_matrix <- function(data = data,
                        k = 3,
                        subsample_prop = 0.8,
                        num_subsamples = 10,
                        start_seed = 123,
                        cluster_method){

  ### INPUT CHECKS:
  # data is a dataframe
  if (!is.data.frame(data)) {
    stop("Data must be in a dataframe.")}

  # k is a positive int
  if (k %% 1 != 0 || k < 1) {
    stop("The desired k value must be a positive integer.")}

  # k is 1
  if (k == 1) {
    warning("The desired k value is 1 (one cluster).")}

  # sub_sample prop is between 0 and 1
  if (subsample_prop <= 0 || subsample_prop >= 1) {
    stop("Subsample proportion needs to be between 0 and 1.")}

  #  num_subsamples is a positive int
  if (num_subsamples <= 0 || num_subsamples %% 1 != 0) {
    stop("The number of subsamples must be a positive integer.")}

  # clustering method is kmeans
  if (cluster_method != "kmeans"){
    stop("Error: Clustering method does not currently work. Please change to 'kmeans'.")}

  # start seed is a positive int
  if (start_seed %% 1 != 0 || start_seed < 0) {
    stop("The seed value must be an integer.")}

  ### FUNCTION:
  # call buddies_matrix()
  results <- buddies_matrix(data,
                            k = k,
                            subsample_prop = subsample_prop,
                            num_subsamples = num_subsamples,
                            start_seed = start_seed,
                            cluster_method = cluster_method)

  # abs value the entire matrix for all matrices
  absolute_sum <- lapply(results, abs)

  # get sum of abs value in final matrix
  absolute_final <- absolute_sum |>
    purrr::reduce(`+`)

  # get sum of values in final matrix
  numerator <- results |>
    purrr::reduce(`+`)

  return(list(matrices = results, score = numerator/absolute_final))}
